### ISSUE TITLE
Store details in Database for the team

### ISSUE THREAD

**Issue by Signior-X** [RobotronicsClubIITMandi/RobotronicsClubWebsite#1]
I was viewing the code and found that all the team members and their details - image url and all are hard coded. This is indeed increasing the code size + making it hard for updation.
So, instead we can add another model and add the details in that. and then using the ejs template engine, we can implement loop and can get the team data.
I don't know much, just a noob still, so asking.

**Comment by dipanshu231099** [comment]
yes dont worry, by the time other things are sorted out we will come back to solve such issues
