### ISSUE TITLE
Query selector for team images

### ISSUE THREAD

**Issue by dipanshu231099** [RobotronicsClubIITMandi/RobotronicsClubWebsite#2]
currently the quesry selector does not initiates correctly. that is, all the memebers of the team are shown in the beginning. this makes the very first page too long to be pleasable to the user. So, change it so that only the mentors are shown first and others as per the click of the user on the respective tab.
Yout may have to use some other query selector if the current one is not working,  or design yourself js file to do so.

**Comment by Signior-X** [comment]
I am doing this one. I have tried this. Making change in the jQuery.
