### ISSUE TITLE
Uniform sizing under Our Projects

### ISSUE THREAD

**Issue by dipanshu231099** [RobotronicsClubIITMandi/RobotronicsClubWebsite#34]
Currently the section for "OUR PROJECTS" contains various boxes that are not all of same vertical height. It would be very pleasing to see uniform boxes rather than the current situation. The height of the boxes in same line should be set to the height of the one having height greater of the two.

**Comment by Shubhanshu0608** [comment]
can I do it?

**Comment by Shubhanshu0608** [comment]
Can I do this?

**Comment by dipanshu231099** [comment]
@Shubhanshu0608 yes go on

**Comment by Signior-X** [comment]
Fixed in #52 
Using min height
