### ISSUE TITLE
Update the current Team.

### ISSUE THREAD

**Issue by Signior-X** [RobotronicsClubIITMandi/RobotronicsClubWebsite#37]
I guess you got it right, get the photos from facebook directly and use them. This is the easiest thing to start with also.
Any help needed for this ask @dipanshu231099 regarding this one.

**Comment by Signior-X** [comment]
@BeingHomosapien if you haven't started, leave it for some new comer. This will be an easy task for them.

**Comment by nehal6657** [comment]
if anyone is not doing it then i can do it

**Comment by dipanshu231099** [comment]
@nehal6657 yes you may start with it. I will assign it to you.
