### ISSUE TITLE
Write something about how you set up you setup starting working on this project in the READMe File.

### ISSUE THREAD

**Issue by Signior-X** [RobotronicsClubIITMandi/RobotronicsClubWebsite#40]
You have to just try how to start a Node.js server and write what steps you did.
Are you able to understand the code?

Just some description which you think will **help new comers to easily understand** and start contribution on this site.

**Comment by Signior-X** [comment]
@prashant280920 have you done this one?

**Comment by dipanshu231099** [comment]
@prashant280920 reply here if you wish to be assigned helps us know better which issues are in progress
