### ISSUE TITLE
Change the route of Inventory at home page

### ISSUE THREAD

**Issue by Signior-X** [RobotronicsClubIITMandi/RobotronicsClubWebsite#42]
The inventory on the top at the navigation bar should directly let the user to go to inventory page, so just change that.
It currently let's to go down, instead make it direct.

**Comment by Shubhanshu0608** [comment]
Ya I am working on this one.

**Comment by Signior-X** [comment]
Ya sure @Shubhanshu0608

**Comment by Signior-X** [comment]
#49
