### ISSUE TITLE
Have a common footer everywhere!

### ISSUE THREAD

**Issue by Signior-X** [RobotronicsClubIITMandi/RobotronicsClubWebsite#43]
The fotter code is jsut copy pasted everywhere, make use of ejs include method to add it everwhere!
This will help in easy and short code!

Need help? 
https://stackoverflow.com/questions/5813771/in-ejs-template-engine-how-do-i-include-a-footer
The first answer will help and don't forget to make a fotter.ejs file

**.ejs file is just an html file**

**Comment by yash-agarwal17** [comment]
Can I work on this?

**Comment by Signior-X** [comment]
Sure go ahead @yash-agarwal17 

Assigning you.

**Comment by Signior-X** [comment]
@yash-agarwal17 sure you start, currently @prashant280920 is working on creating a contribution file to help one start the server.
Still here are some steps you need to 
First clone the repo, then 
Go to the main_site directory.

From there do the
```
npm install
``` 
Then you need to create a folder named `config` in the main_site folder, and add the file named `development.json`
with the following data
```
{
    "name": "Development Mode",
    "dbUrl": "create a mongoDB atlas server and add the connection String here",
    "adminUsername": "admin",
    "adminPassword": "admin",
    "mailFromEmail": "",
    "mailFromPassword": "",
    "mailToEmail": ""
}
```

Change the dbUrl with the mongoDb url, you are using, you may use the local mongoDb server or atlas for development.

**Comment by Signior-X** [comment]
You can also use nodemon to start the development server.

**Comment by Signior-X** [comment]
@yash-agarwal17 you can check the https://github.com/RobotronicsClubIITMandi/RobotronicsClubWebsite/blob/master/contributors.md for more info now.

**Comment by prashant280920** [comment]
@Signior-X can i work on it?

**Comment by dipanshu231099** [comment]
@prashant280920 anyone is free to open a PR.
