### ISSUE TITLE
maximum number of objects

### ISSUE THREAD

**Issue by dipanshu231099** [RobotronicsClubIITMandi/RobotronicsClubWebsite#9]
the number of objects displayed on the home screen is equal to the objects actually present however that is not required as for the news only show the latest 3, for projects the top 4 and for admin page it is useless to show more than 10 notifications i guess... so for admin page keep the limit to just 10 top notifications and all projects.

**Comment by BeingHomosapien** [comment]
I am doing it

**Comment by dipanshu231099** [comment]
solved.
